spring:
  datasource:
#    url: jdbc:mysql://192.168.182.13:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
    url: jdbc:mysql://192.168.182.13:3306/springboot
