server:
  port: 9000
spring:
  application:
    name: Spring Boot Admin Web
#  boot:
#    admin:
#      probed-endpoints: {env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,
#                        showEndpoints,serverEndpoint}
management:
  endpoints:
    web:
      exposure:
        include: {env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,
                                  showEndpoints,serverEndpoint}
